# Generated by Django 5.2.4 on 2025-07-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korrupsiya_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KorrupsiyaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='korrupsiya_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='karrupsiyamalumot',
            name='file',
        ),
    ]
