# Generated by Django 5.2.4 on 2026-06-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korrupsiya_app', '0002_vacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Murojaat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='murojaatlar/')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('tushuntirildi', 'Tushuntirildi'), ('qoniqtirildi', 'Qoniqtirildi'), ('rad_etildi', 'Rad etildi')], default='new', max_length=20)),
                ('assigned_telegram_chat_id', models.CharField(blank=True, max_length=64)),
                ('telegram_sent_at', models.DateTimeField(blank=True, null=True)),
                ('telegram_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
