# Generated by Django 5.2.4 on 2026-06-05 12:20

from django.db import migrations, models


def create_telegram_settings_if_missing(apps, schema_editor):
    TelegramSettings = apps.get_model("korrupsiya_app", "TelegramSettings")
    existing_tables = schema_editor.connection.introspection.table_names()
    if TelegramSettings._meta.db_table in existing_tables:
        return
    schema_editor.create_model(TelegramSettings)


class Migration(migrations.Migration):

    dependencies = [
        ("korrupsiya_app", "0003_murojaat"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    create_telegram_settings_if_missing,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="TelegramSettings",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("bot_token", models.CharField(blank=True, max_length=255)),
                        ("admin_chat_id", models.CharField(blank=True, max_length=64)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        "verbose_name": "Telegram sozlamasi",
                        "verbose_name_plural": "Telegram sozlamalari",
                    },
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="murojaat",
            name="assigned_telegram_chat_id",
        ),
        migrations.RemoveField(
            model_name="murojaat",
            name="telegram_error",
        ),
        migrations.RemoveField(
            model_name="murojaat",
            name="telegram_sent_at",
        ),
    ]
